services:
  fyr:
    image: ghcr.io/hen-io/fyr:latest
    container_name: fyr
    ports:
      - "80:80"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ../Fyr-data/config:/config
      - ../Fyr-data/data:/data
